# Generated by Django 2.2.5 on 2019-10-29 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sponsor',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('phoneNum', models.IntegerField()),
                ('idNum', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
    ]
