# Generated by Django 2.2.5 on 2019-10-29 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fundraiser',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('phoneNum', models.IntegerField()),
                ('idNum', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Projects',
            fields=[
                ('name', models.CharField(max_length=10)),
                ('idNum', models.AutoField(primary_key=True, serialize=False)),
            ],
        ),
    ]
