# Generated by Django 2.2.5 on 2019-11-05 08:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfunding', '0003_auto_20191029_2041'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('admin_id', models.AutoField(primary_key=True, serialize=False)),
                ('admin_name', models.CharField(max_length=18)),
                ('admin_pwd', models.CharField(max_length=16)),
                ('admin_mobile', models.CharField(max_length=11)),
                ('admin_real_name', models.CharField(max_length=10, null=True)),
                ('admin_card', models.CharField(max_length=18, null=True)),
                ('admin_career', models.CharField(max_length=100, null=True)),
                ('admin_image', models.CharField(max_length=20000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('task_id', models.AutoField(primary_key=True, serialize=False)),
                ('task_card', models.CharField(max_length=100)),
                ('task_name', models.CharField(max_length=10)),
                ('task_money', models.FloatField()),
                ('task_cost', models.CharField(max_length=100)),
                ('task_type_choices', models.CharField(choices=[('PWCF', 'PWCF'), ('PCF', 'PCF')], default='PWCF', max_length=2)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('user_name', models.CharField(max_length=18)),
                ('user_pwd', models.CharField(max_length=16)),
                ('user_mobile', models.CharField(max_length=11)),
                ('user_real_name', models.CharField(max_length=10, null=True)),
                ('user_card', models.CharField(max_length=18, null=True)),
                ('user_career', models.CharField(max_length=100, null=True)),
                ('user_image', models.CharField(max_length=20000, null=True)),
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_adress', models.CharField(max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Fundraisers',
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Sponsor',
        ),
        migrations.AddField(
            model_name='task',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfunding.User'),
        ),
    ]
